---
- name: Install 'mariadb-server' and 'MySQL-python' packages
  yum:
    name:
    - MySQL-python
    - mariadb-server
    update_cache: true
    state: present

- name: Ensure 'mariadb' service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create "{{ wp_db_name }}" database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: >
    Create database user "{{ wp_db_user }}" with "{{ wp_db_password }}"
    and "{{ wp_db_name }}".*:ALL privelege
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
  no_log: true